import 'katex/dist/katex.min.css';
import formulas from './prerendered-formulas.json';

type Key = keyof typeof formulas;

/**
 * Renders a build-time pre-rendered KaTeX formula. The HTML is produced by
 * scripts/prerender-formulas.mjs in Node (where KaTeX is correct) and injected
 * here, sidestepping the Vite 8 bundler bug that corrupts KaTeX in the browser.
 * The HTML is generated by our own trusted build step — not user input.
 */
export function Tex({ name, className }: { name: Key; className?: string }) {
  return <span className={className} dangerouslySetInnerHTML={{ __html: formulas[name] }} />;
}

/** Block (display) variant — just a convenience wrapper for layout. */
export function TexBlock({ name, className = '' }: { name: Key; className?: string }) {
  return <div className={className} dangerouslySetInnerHTML={{ __html: formulas[name] }} />;
}
